# Generated by Django 5.2.8 on 2026-01-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=300)),
                ('api_enabled', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('logged_in', models.BooleanField(default=False)),
            ],
        ),
    ]
