# Generated by Django 5.2.8 on 2026-01-15 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests', models.IntegerField(blank=True, default=0)),
                ('ip', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_enabled', models.BooleanField(default=False)),
                ('token', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=300)),
                ('logged_in', models.BooleanField(default=False)),
                ('logs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dict_auth.log')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
