# Generated by Django 5.2.8 on 2026-01-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
