# Generated by Django 5.2.8 on 2026-01-15 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_auth', '0002_alter_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='logs',
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dict_auth.profile'),
        ),
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='requests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
